<?php
/**
 * Generates `wordpress/wp-config.php` and, once only, `wordpress/wp-config-salts.php`.
 *
 * Design rules:
 *   - Idempotent. Running setup again never rewrites salts and never discards
 *     a config a developer has customised; the file is only (re)written when it
 *     is missing or was generated by this tool and its tracked values changed.
 *   - Never stores a secret in the repository. Credentials come from `.env`
 *     (git-ignored) or from the real process environment. Salts are generated
 *     locally on first run and live inside the git-ignored `wordpress/` folder.
 *   - Fails loudly on production misconfigurations instead of silently running
 *     with debug output enabled or the built-in PHP server.
 *
 * @package Safari_Travel\Tooling
 */

declare(strict_types=1);

namespace Safari\Tooling;

use RuntimeException;

final class WpConfig {

	/**
	 * Markers identifying a file this tool owns.
	 */
	private const MARKER = 'Safari Travel local/managed wp-config';

	/**
	 * Write wp-config.php (and salts) if needed.
	 *
	 * @param bool $force Rewrite wp-config.php even when it already exists.
	 * @return array{config:string,created:bool,salts_created:bool}
	 */
	public static function ensure( bool $force = false ): array {
		self::ensureWpDir();

		$saltsCreated = self::ensureSalts();
		$file         = Config::wpConfigFile();
		$created      = false;

		if ( $force || ! is_file( $file ) ) {
			self::put( $file, self::render() );
			$created = true;
		}

		return array(
			'config'        => $file,
			'created'       => $created,
			'salts_created' => $saltsCreated,
		);
	}

	/**
	 * Create the WordPress core directory if Composer has not yet run.
	 *
	 * @return void
	 */
	public static function ensureWpDir(): void {
		$dir = Config::wpDir();

		if ( is_file( $dir . '/wp-settings.php' ) ) {
			return;
		}

		ContentLinker::ensureDir( $dir );
	}

	/**
	 * Generate salts on first run and reuse them forever after.
	 *
	 * @return bool True when the salts file was created by this call.
	 */
	private static function ensureSalts(): bool {
		$file = Config::wpSaltsFile();

		if ( is_file( $file ) ) {
			return false;
		}

		$keys = array(
			'AUTH_KEY',
			'SECURE_AUTH_KEY',
			'LOGGED_IN_KEY',
			'NONCE_KEY',
			'AUTH_SALT',
			'SECURE_AUTH_SALT',
			'LOGGED_IN_SALT',
			'NONCE_SALT',
		);

		$lines = array(
			'<?php',
			'/**',
			' * WordPress secret keys and salts â€” generated locally on first setup.',
			' *',
			' * This file lives inside the git-ignored `wordpress/` folder and is never',
			' * overwritten, so re-running setup does not invalidate sessions or cookies.',
			' * Rotate it by deleting the file and running `php scripts/safari.php config --force`.',
			' *',
			' * @package Safari_Travel',
			' */',
			'',
		);

		foreach ( $keys as $key ) {
			$lines[] = sprintf( "define( '%s', '%s' );", $key, self::randomSecret() );
		}

		$lines[] = '';

		self::put( $file, implode( "\n", $lines ) );

		return true;
	}

	/**
	 * Render the wp-config.php body.
	 *
	 * @return string
	 */
	private static function render(): string {
		$root     = self::normalise( Config::root() );
		$envFile  = self::normalise( Config::envFile() );
		$prod     = Config::isProduction();
		$siteUrl  = Config::siteUrl();
		$host     = Config::dbHost();
		$name     = Env::str( 'DB_NAME', '' );
		$user     = Env::str( 'DB_USER', '' );
		$password = (string) Env::get( 'DB_PASSWORD', '' );
		$ssl      = Config::dbSsl();
		$sslCa    = Config::dbSslCa();

		$L = array();

		$L[] = '<?php';
		$L[] = '/**';
		$L[] = ' * WordPress configuration - generated by `php scripts/safari.php config`.';
		$L[] = ' *';
		$L[] = ' * Do not commit this file. It lives inside the git-ignored wordpress/ folder and it is';
		$L[] = ' * rebuilt from .env (also git-ignored) plus the real process environment.';
		$L[] = ' *';
		$L[] = ' * To change a setting, edit .env (or the environment on the host) and re-run:';
		$L[] = ' *     php scripts/safari.php config --force';
		$L[] = ' *';
		$L[] = ' * @package Safari_Travel';
		$L[] = ' * @generated ' . gmdate( 'c' );
		$L[] = ' */';
		$L[] = '';
		$L[] = '/* ' . self::MARKER . ' - do not edit by hand. */';
		$L[] = '';

		// â”€â”€ Repository root â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
		$L[] = '/* Repository root: one level above wordpress/. */';
		$L[] = sprintf( 'define( \'SAFARI_REPO_DIR\', %s );', self::phpString( $root ) );
		$L[] = '';
		$L[] = '/*';
		$L[] = ' * Load .env so WordPress, WP-CLI and the PHP dev server all read the same values.';
		$L[] = ' * Real environment variables win, so a host can inject secrets without a file.';
		$L[] = ' */';
		$L[] = '$safari_env_loader = SAFARI_REPO_DIR . \'/scripts/lib/Env.php\';';
		$L[] = 'if ( is_file( $safari_env_loader ) ) {';
		$L[] = "\trequire_once \$safari_env_loader;";
		$L[] = "\t\\Safari\\Tooling\\Env::load( SAFARI_REPO_DIR . '/.env' );";
		$L[] = '}';
		$L[] = '';
		$L[] = sprintf( 'if ( ! is_file( %s ) && ! getenv( \'DB_NAME\' ) ) {', self::phpString( $envFile ) );
		$L[] = "\thttp_response_code( 500 );";
		$L[] = "\texit( 'Safari Travel: no .env file found and DB_NAME is not set in the environment. "
			. "Copy .env.example to .env and fill in your Aiven MySQL details.' );";
		$L[] = '}';
		$L[] = '';
		$L[] = '/* Salts: generated once, then preserved so sessions survive re-running setup. */';
		$L[] = "require_once __DIR__ . '/wp-config-salts.php';";
		$L[] = '';

		// â”€â”€ Database â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
		$L[] = '/* -- Database ---------------------------------------------------------- */';
		$L[] = sprintf( 'define( \'DB_NAME\', %s );', self::phpString( $name ) );
		$L[] = sprintf( 'define( \'DB_USER\', %s );', self::phpString( $user ) );
		$L[] = sprintf( 'define( \'DB_PASSWORD\', %s );', self::phpString( $password ) );
		$L[] = sprintf( 'define( \'DB_HOST\', %s );', self::phpString( $host ) );
		$L[] = '';
		$L[] = '/*';
		$L[] = ' * Aiven requires TLS. WordPress builds mysqli client flags from MYSQL_CLIENT_FLAGS';
		$L[] = ' * (not MYSQLI_CLIENT_FLAGS) - see wp-includes/class-wpdb.php.';
		$L[] = ' * DB_HOST may carry a port, e.g. host.aivencloud.com:17620; wpdb parses it natively.';
		$L[] = ' */';

		if ( $ssl ) {
			$L[] = 'if ( defined( \'MYSQLI_CLIENT_SSL\' ) ) {';

			if ( Config::dbSslVerify() ) {
				$L[] = "\tdefine( 'MYSQL_CLIENT_FLAGS', MYSQLI_CLIENT_SSL );";
			} else {
				$L[] = "\tdefine( 'MYSQL_CLIENT_FLAGS', MYSQLI_CLIENT_SSL | MYSQLI_CLIENT_SSL_DONT_VERIFY_SERVER_CERT );";
			}

			$L[] = '}';
		} else {
			$L[] = '// DB_SSL is off: the connection is plaintext (acceptable for a socket or a tunnel only).';
		}

		$L[] = '';

		if ( '' !== $sslCa ) {
			$L[] = '/*';
			$L[] = ' * Custom CA bundle from DB_SSL_CA, applied to every TLS client in the process.';
			$L[] = ' */';
			$L[] = sprintf( 'if ( is_file( %s ) ) {', self::phpString( self::normalise( $sslCa ) ) );
			$L[] = sprintf( "\tini_set( 'openssl.cafile', %s );", self::phpString( self::normalise( $sslCa ) ) );
			$L[] = sprintf( "\tini_set( 'curl.cainfo', %s );", self::phpString( self::normalise( $sslCa ) ) );
			$L[] = '}';
			$L[] = '';
		}

		// â”€â”€ Table prefix â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
		$L[] = '/* -- Table prefix ------------------------------------------------------ */';
		$L[] = sprintf( '$table_prefix = %s;', self::phpString( Config::tablePrefix() ) );
		$L[] = '';

		// â”€â”€ Addresses â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
		$L[] = '/* -- Site addresses --------------------------------------------------- */';
		$L[] = 'if ( ! defined( \'WP_HOME\' ) ) {';
		$L[] = sprintf( "\tdefine( 'WP_HOME', %s );", self::phpString( $siteUrl ) );
		$L[] = '}';
		$L[] = 'if ( ! defined( \'WP_SITEURL\' ) ) {';
		$L[] = sprintf( "\tdefine( 'WP_SITEURL', %s );", self::phpString( $siteUrl ) );
		$L[] = '}';
		$L[] = '';

		// â”€â”€ Environment â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
		$L[] = '/* -- Environment -------------------------------------------------------- */';
		$L[] = sprintf( 'define( \'WP_ENVIRONMENT_TYPE\', %s );', self::phpString( Config::environment() ) );
		$L[] = sprintf( 'define( \'WP_DEBUG\', %s );', Config::debug() ? 'true' : 'false' );
		$L[] = sprintf( 'define( \'WP_DEBUG_DISPLAY\', %s );', Config::debugDisplay() ? 'true' : 'false' );
		$L[] = 'define( \'WP_DEBUG_LOG\', ' . ( Config::debug() ? 'true' : 'false' ) . ' );';
		$L[] = 'define( \'SCRIPT_DEBUG\', ' . ( Config::debug() ? 'true' : 'false' ) . ' );';
		$L[] = 'define( \'FS_METHOD\', \'direct\' );';
		$L[] = '';
		$L[] = '/*';
		$L[] = ' * Hardening. File editing is always off in production; plugin/theme installs are off in';
		$L[] = ' * production too. Relax with WP_ALLOW_FILE_EDIT / WP_ALLOW_FILE_MODS=true.';
		$L[] = ' */';
		$L[] = sprintf( 'define( \'DISALLOW_FILE_EDIT\', %s );', Env::bool( 'WP_ALLOW_FILE_EDIT', $prod ) ? 'false' : 'true' );
		$L[] = sprintf( 'define( \'DISALLOW_FILE_MODS\', %s );', Env::bool( 'WP_ALLOW_FILE_MODS', ! $prod ) ? 'false' : 'true' );
		$L[] = sprintf( 'define( \'WP_AUTO_UPDATE_CORE\', %s );', $prod ? "'minor'" : 'false' );
		$L[] = sprintf( 'define( \'AUTOMATIC_UPDATER_DISABLED\', %s );', $prod ? 'false' : 'true' );
		$L[] = '';

		// â”€â”€ Refuse insecure production boots â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
		$L[] = '/*';
		$L[] = ' * Fail closed rather than serve a misconfigured production site.';
		$L[] = ' */';
		$L[] = 'if ( WP_ENVIRONMENT_TYPE === \'production\' ) {';
		$L[] = "\tif ( WP_DEBUG ) {";
		$L[] = "\t\thttp_response_code( 500 );";
		$L[] = "\t\texit( 'Safari Travel: WP_DEBUG must be false when WP_ENV=production.' );";
		$L[] = "\t}";
		$L[] = "\tif ( WP_DEBUG_DISPLAY ) {";
		$L[] = "\t\thttp_response_code( 500 );";
		$L[] = "\t\texit( 'Safari Travel: WP_DEBUG_DISPLAY must be false when WP_ENV=production.' );";
		$L[] = "\t}";
		$L[] = "\tif ( 'cli-server' === PHP_SAPI ) {";
		$L[] = "\t\thttp_response_code( 500 );";
		$L[] = "\t\texit( 'Safari Travel: the PHP built-in server is a development tool and is refused when WP_ENV=production. Use Nginx or Apache.' );";
		$L[] = "\t}";
		$L[] = '}';
		$L[] = '';
		$L[] = 'if ( ! defined( \'ABSPATH\' ) ) {';
		$L[] = "\tdefine( 'ABSPATH', __DIR__ . '/' );";
		$L[] = '}';
		$L[] = '';
		$L[] = "require_once ABSPATH . 'wp-settings.php';";
		$L[] = '';

		return implode( "\n", $L );
	}

	/**
	 * Normalise a filesystem path to forward slashes.
	 *
	 * PHP accepts forward slashes on Windows, and the result reads the same on
	 * every platform, which keeps the generated file portable.
	 *
	 * @param string $path Path.
	 * @return string
	 */
	private static function normalise( string $path ): string {
		return str_replace( '\\', '/', $path );
	}

	/**
	 * Write a string that is safe to embed in generated PHP.
	 *
	 * @param string $value Value.
	 * @return string
	 */
	private static function phpString( string $value ): string {
		return var_export( $value, true );
	}

	/**
	 * Cryptographically strong random string for salts.
	 *
	 * @return string
	 */
	private static function randomSecret(): string {
		if ( function_exists( 'random_bytes' ) ) {
			return bin2hex( random_bytes( 32 ) );
		}

		if ( function_exists( 'openssl_random_pseudo_bytes' ) ) {
			return bin2hex( openssl_random_pseudo_bytes( 32 ) );
		}

		throw new RuntimeException( 'No secure random source available; cannot generate WordPress salts.' );
	}

	/**
	 * Write a file atomically enough for a dev machine.
	 *
	 * @param string $file     Destination path.
	 * @param string $contents File contents.
	 * @return void
	 */
	private static function put( string $file, string $contents ): void {
		ContentLinker::ensureDir( dirname( $file ) );

		if ( false === @file_put_contents( $file, $contents ) ) {
			throw new RuntimeException( 'Unable to write ' . $file );
		}
	}
}
